/**
 * API Contracts - Request & Response Type Definitions
 *
 * Auto-generated by scripts/sync-openapi-types.mjs
 * Run `npm run openapi:sync` to regenerate.
 * DO NOT modify this file manually.
 */

import type { paths as AuthPaths } from './api.auth.generated'
import type { paths as EmailPaths } from './api.email.generated'
import type { paths as FeedbackPaths } from './api.feedback.generated'
import type { paths as SystemPaths } from './api.system.generated'

// ============================================================================
// AUTH API
// ============================================================================

/** Register with email and password */
export type AuthRegisterRequest =
  AuthPaths['/api/auth/register']['post']['requestBody']['content']['application/json']
export type AuthRegisterResponse =
  AuthPaths['/api/auth/register']['post']['responses']['201']['content']['application/json']

/** Login with email and password */
export type AuthLoginRequest =
  AuthPaths['/api/auth/login']['post']['requestBody']['content']['application/json']
export type AuthLoginResponse =
  AuthPaths['/api/auth/login']['post']['responses']['200']['content']['application/json']

/** Login or register with Google ID token */
export type AuthGoogleRequest =
  AuthPaths['/api/auth/google']['post']['requestBody']['content']['application/json']
export type AuthGoogleResponse =
  AuthPaths['/api/auth/google']['post']['responses']['200']['content']['application/json']

/** Request a password reset link via email */
export type AuthForgotPasswordRequest =
  AuthPaths['/api/auth/forgot-password']['post']['requestBody']['content']['application/json']
export type AuthForgotPasswordResponse =
  AuthPaths['/api/auth/forgot-password']['post']['responses']['200']['content']['application/json']

/** Reset password using token from reset email */
export type AuthResetPasswordRequest =
  AuthPaths['/api/auth/reset-password']['post']['requestBody']['content']['application/json']
export type AuthResetPasswordResponse =
  AuthPaths['/api/auth/reset-password']['post']['responses']['200']['content']['application/json']

// ============================================================================
// EMAIL API
// ============================================================================

/** Send a verification code to email */
export type EmailSendCodeRequest =
  EmailPaths['/api/email/send-code']['post']['requestBody']['content']['application/json']
export type EmailSendCodeResponse =
  EmailPaths['/api/email/send-code']['post']['responses']['201']['content']['application/json']

/** Verify email code and get user token */
export type EmailVerifyRequest =
  EmailPaths['/api/email/verify']['post']['requestBody']['content']['application/json']
export type EmailVerifyResponse =
  EmailPaths['/api/email/verify']['post']['responses']['200']['content']['application/json']

// ============================================================================
// FEEDBACK API
// ============================================================================

/** Submit anonymous feedback (no authentication required) */
export type FeedbackAnonymousSubmitRequest =
  FeedbackPaths['/api/feedback/anonymous/submit']['post']['requestBody']['content']['application/json']
export type FeedbackAnonymousSubmitResponse =
  FeedbackPaths['/api/feedback/anonymous/submit']['post']['responses']['201']['content']['application/json']

/** Bind email to anonymous feedback for follow-up */
export type FeedbackAnonymousBindEmailRequest =
  FeedbackPaths['/api/feedback/anonymous/bind-email']['post']['requestBody']['content']['application/json']
export type FeedbackAnonymousBindEmailResponse =
  FeedbackPaths['/api/feedback/anonymous/bind-email']['post']['responses']['200']['content']['application/json']

/** List feedback with filters and pagination */
export type FeedbackListResponse =
  FeedbackPaths['/api/feedback']['get']['responses']['200']['content']['application/json']

/** Submit feedback with authentication token */
export type FeedbackPostRequest =
  FeedbackPaths['/api/feedback']['post']['requestBody']['content']['application/json']
export type FeedbackPostResponse =
  FeedbackPaths['/api/feedback']['post']['responses']['201']['content']['application/json']

/** Add customer follow-up message to feedback thread */
export type FeedbackFollowUpRequest =
  FeedbackPaths['/api/feedback/{feedbackId}/follow-up']['post']['requestBody']['content']['application/json']
export type FeedbackFollowUpResponse =
  FeedbackPaths['/api/feedback/{feedbackId}/follow-up']['post']['responses']['201']['content']['application/json']

/** Get feedback thread conversation (for user: only their own, for admin: any) */
export type FeedbackThreadResponse =
  FeedbackPaths['/api/feedback/{feedbackId}/thread']['get']['responses']['200']['content']['application/json']

// ============================================================================
// SYSTEM API
// ============================================================================

/** Generate a signed upload URL for GCS */
export type StorageSignedUploadUrlRequest =
  SystemPaths['/api/storage/signed-upload-url']['post']['requestBody']['content']['application/json']
export type StorageSignedUploadUrlResponse =
  SystemPaths['/api/storage/signed-upload-url']['post']['responses']['200']['content']['application/json']

// ============================================================================
// Namespace Exports (for grouped access by module)
// ============================================================================
export * as Auth from './api.auth.generated'
export * as Email from './api.email.generated'
export * as Feedback from './api.feedback.generated'
export * as System from './api.system.generated'

// ============================================================================
// HELPER TYPES - Auto-extracted from API schemas
// ============================================================================

/** identity */
export type AuthIdentity =
  NonNullable<NonNullable<AuthRegisterResponse['data']>>['identity']

/** identity */
export type EmailIdentity =
  NonNullable<NonNullable<EmailVerifyResponse['data']>>['identity']

/** type enum */
export type FeedbackType =
  NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['type']

/** status enum */
export type FeedbackStatus =
  NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['status']

/** locale enum */
export type FeedbackLocale =
  NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['locale']

/** submitMode enum */
export type FeedbackSubmitMode =
  NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['submitMode']

/** attachments item */
export type FeedbackAttachment =
  NonNullable<NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['attachments']>[number]

/** tagMaps item */
export type FeedbackTagMap =
  NonNullable<NonNullable<NonNullable<NonNullable<FeedbackAnonymousSubmitResponse['data']>>['feedback']>['tagMaps']>[number]

/** items item */
export type FeedbackItem =
  NonNullable<NonNullable<NonNullable<FeedbackListResponse['data']>>['items']>[number]

/** paginationMode enum */
export type FeedbackPaginationMode =
  NonNullable<NonNullable<FeedbackListResponse['data']>>['paginationMode']

/** firstCustomerMessage */
export type FeedbackFirstCustomerMessage =
  NonNullable<NonNullable<FeedbackPostResponse['data']>>['firstCustomerMessage']

/** sender enum */
export type FeedbackSender =
  NonNullable<NonNullable<NonNullable<FeedbackPostResponse['data']>>['firstCustomerMessage']>['sender']

/** identity */
export type FeedbackIdentity =
  NonNullable<NonNullable<FeedbackPostResponse['data']>>['identity']

/** mode enum */
export type FeedbackMode =
  NonNullable<NonNullable<NonNullable<FeedbackPostResponse['data']>>['identity']>['mode']

/** /api/feedback/{feedbackId}/follow-up */
export type FeedbackFollowUp =
  NonNullable<FeedbackFollowUpResponse['data']>

/** /api/feedback/{feedbackId}/thread */
export type FeedbackThread =
  NonNullable<FeedbackThreadResponse['data']>

/** messages item */
export type FeedbackMessage =
  NonNullable<NonNullable<NonNullable<FeedbackThreadResponse['data']>>['messages']>[number]

/** tags item */
export type FeedbackTag =
  NonNullable<NonNullable<NonNullable<FeedbackThreadResponse['data']>>['tags']>[number]

/** requiredHeaders */
export type StorageRequiredHeaders =
  NonNullable<NonNullable<StorageSignedUploadUrlResponse['data']>>['requiredHeaders']

/** uploadConstraints */
export type StorageUploadConstraints =
  NonNullable<NonNullable<StorageSignedUploadUrlResponse['data']>>['uploadConstraints']

/** scope enum */
export type StorageScope =
  NonNullable<NonNullable<NonNullable<StorageSignedUploadUrlResponse['data']>>['uploadConstraints']>['scope']
