/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/feedback/anonymous/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Submit anonymous feedback (no authentication required) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "bug" | "feature" | "experience" | "other";
                        content: string;
                        rating: number;
                        /** @default [] */
                        attachments?: {
                            /** Format: uri */
                            url: string;
                            filename: string;
                            size: number;
                        }[];
                        /**
                         * @default zh-CN
                         * @enum {string}
                         */
                        locale?: "zh-CN" | "zh-Hant" | "en";
                    };
                };
            };
            responses: {
                /** @description Anonymous feedback submitted */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                anonymousId: string;
                                feedback: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    type: "bug" | "feature" | "experience" | "other";
                                    rating: number;
                                    contact: string | null;
                                    allowContact: boolean;
                                    /** @enum {string} */
                                    status: "new" | "reviewed" | "replied" | "renew" | "resolved";
                                    /** @enum {string} */
                                    locale: "zh_CN" | "zh_Hant" | "en";
                                    /** @enum {string} */
                                    submitMode: "anonymous" | "email";
                                    identityId: string | null;
                                    firstCustomerMessageId: string | null;
                                    latestAdminReply: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    firstCustomerMessage: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        feedbackId: string;
                                        /** @enum {string} */
                                        sender: "customer" | "admin";
                                        senderId: string | null;
                                        content: string;
                                        isQuestion: boolean;
                                        inReplyToMessageId: string | null;
                                        idempotencyKey: string | null;
                                        /** Format: date-time */
                                        createdAt: string;
                                    } | null;
                                    attachments: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        feedbackId: string;
                                        /** Format: uuid */
                                        messageId: string;
                                        /** Format: uri */
                                        url: string;
                                        filename: string;
                                        sizeBytes: number;
                                        /** Format: date-time */
                                        createdAt: string;
                                    }[];
                                    identity: {
                                        /** Format: uuid */
                                        id: string;
                                        /** @enum {string} */
                                        mode: "anonymous" | "email";
                                        anonymousId: string;
                                        email: string | null;
                                        emailVerifiedAt: string | null;
                                        isEmailBound: boolean;
                                        /** Format: date-time */
                                        createdAt: string;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    tagMaps: {
                                        /** Format: uuid */
                                        feedbackId: string;
                                        tagId: number;
                                        /** Format: date-time */
                                        createdAt: string;
                                        tag: {
                                            id: number;
                                            name: string;
                                        };
                                    }[];
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/anonymous/bind-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Bind email to anonymous feedback for follow-up */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        anonymousId: string;
                        /** Format: email */
                        email: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Email bound successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                anonymousId: string;
                                email: string | null;
                                emailVerifiedAt: string | null;
                                isEmailBound: boolean;
                                /** @enum {boolean} */
                                merged: false;
                            } | {
                                anonymousId: null;
                                email: string | null;
                                emailVerifiedAt: string | null;
                                isEmailBound: boolean;
                                /** @enum {boolean} */
                                merged: true;
                                mergedFeedbackCount: number;
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List feedback with filters and pagination */
        get: {
            parameters: {
                query?: {
                    firstQuestionKeyword?: string;
                    keyword?: string;
                    status?: "new" | "reviewed" | "replied" | "renew" | "resolved";
                    type?: "bug" | "feature" | "experience" | "other";
                    locale?: "zh-CN" | "zh-Hant" | "en";
                    contact?: string;
                    ratingMin?: number;
                    ratingMax?: number;
                    isResolved?: "true" | "false";
                    hasAttachment?: "true" | "false";
                    archived?: "true" | "false";
                    tags?: string;
                    from?: string;
                    to?: string;
                    sortBy?: "createdAt_desc" | "createdAt_asc" | "rating_desc" | "rating_asc" | "updatedAt_desc" | "updatedAt_asc";
                    paginationMode?: "offset" | "cursor";
                    page?: number;
                    pageSize?: number;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of feedback items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    type: "bug" | "feature" | "experience" | "other";
                                    rating: number;
                                    messageCount: number;
                                    contact: string | null;
                                    allowContact: boolean;
                                    /** @enum {string} */
                                    status: "new" | "reviewed" | "replied" | "renew" | "resolved";
                                    /** @enum {string} */
                                    locale: "zh_CN" | "zh_Hant" | "en";
                                    /** @enum {string} */
                                    submitMode: "anonymous" | "email";
                                    identityId: string | null;
                                    firstCustomerMessageId: string | null;
                                    latestAdminReply: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    firstCustomerMessage: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        feedbackId: string;
                                        /** @enum {string} */
                                        sender: "customer" | "admin";
                                        senderId: string | null;
                                        content: string;
                                        isQuestion: boolean;
                                        inReplyToMessageId: string | null;
                                        idempotencyKey: string | null;
                                        /** Format: date-time */
                                        createdAt: string;
                                    } | null;
                                    identity: {
                                        /** Format: uuid */
                                        id: string;
                                        /** @enum {string} */
                                        mode: "anonymous" | "email";
                                        anonymousId: string;
                                        email: string | null;
                                        emailVerifiedAt: string | null;
                                        isEmailBound: boolean;
                                        /** Format: date-time */
                                        createdAt: string;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    tagMaps: {
                                        /** Format: date-time */
                                        createdAt: string;
                                        tag: {
                                            id: number;
                                            name: string;
                                        };
                                    }[];
                                    attachments: {
                                        /** Format: uuid */
                                        id: string;
                                    }[];
                                }[];
                                /** @enum {string} */
                                paginationMode: "cursor";
                                limit: number;
                                nextCursor: string | null;
                                hasNextPage: boolean;
                            } | {
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    type: "bug" | "feature" | "experience" | "other";
                                    rating: number;
                                    messageCount: number;
                                    contact: string | null;
                                    allowContact: boolean;
                                    /** @enum {string} */
                                    status: "new" | "reviewed" | "replied" | "renew" | "resolved";
                                    /** @enum {string} */
                                    locale: "zh_CN" | "zh_Hant" | "en";
                                    /** @enum {string} */
                                    submitMode: "anonymous" | "email";
                                    identityId: string | null;
                                    firstCustomerMessageId: string | null;
                                    latestAdminReply: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                    firstCustomerMessage: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uuid */
                                        feedbackId: string;
                                        /** @enum {string} */
                                        sender: "customer" | "admin";
                                        senderId: string | null;
                                        content: string;
                                        isQuestion: boolean;
                                        inReplyToMessageId: string | null;
                                        idempotencyKey: string | null;
                                        /** Format: date-time */
                                        createdAt: string;
                                    } | null;
                                    identity: {
                                        /** Format: uuid */
                                        id: string;
                                        /** @enum {string} */
                                        mode: "anonymous" | "email";
                                        anonymousId: string;
                                        email: string | null;
                                        emailVerifiedAt: string | null;
                                        isEmailBound: boolean;
                                        /** Format: date-time */
                                        createdAt: string;
                                        /** Format: date-time */
                                        updatedAt: string;
                                    } | null;
                                    tagMaps: {
                                        /** Format: date-time */
                                        createdAt: string;
                                        tag: {
                                            id: number;
                                            name: string;
                                        };
                                    }[];
                                    attachments: {
                                        /** Format: uuid */
                                        id: string;
                                    }[];
                                }[];
                                /** @enum {string} */
                                paginationMode: "offset";
                                total: number;
                                page: number;
                                pageSize: number;
                                totalPages: number;
                                hasNextPage: boolean;
                                hasPrevPage: boolean;
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code?: string;
                            /** @example Missing or invalid authorization header */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** @description Submit feedback with authentication token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        type: "bug" | "feature" | "experience" | "other";
                        content: string;
                        rating: number;
                        contact?: string;
                        /** @default true */
                        allowContact?: boolean;
                        /** @default [] */
                        attachments?: {
                            /** Format: uri */
                            url: string;
                            filename: string;
                            size: number;
                        }[];
                        /**
                         * @default zh-CN
                         * @enum {string}
                         */
                        locale?: "zh-CN" | "zh-Hant" | "en";
                    };
                };
            };
            responses: {
                /** @description Feedback submitted successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                type: "bug" | "feature" | "experience" | "other";
                                rating: number;
                                contact: string | null;
                                allowContact: boolean;
                                /** @enum {string} */
                                status: "new" | "reviewed" | "replied" | "renew" | "resolved";
                                /** @enum {string} */
                                locale: "zh_CN" | "zh_Hant" | "en";
                                /** @enum {string} */
                                submitMode: "anonymous" | "email";
                                identityId: string | null;
                                firstCustomerMessageId: string | null;
                                latestAdminReply: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                firstCustomerMessage: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: uuid */
                                    feedbackId: string;
                                    /** @enum {string} */
                                    sender: "customer" | "admin";
                                    senderId: string | null;
                                    content: string;
                                    isQuestion: boolean;
                                    inReplyToMessageId: string | null;
                                    idempotencyKey: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                } | null;
                                attachments: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: uuid */
                                    feedbackId: string;
                                    /** Format: uuid */
                                    messageId: string;
                                    /** Format: uri */
                                    url: string;
                                    filename: string;
                                    sizeBytes: number;
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    mode: "anonymous" | "email";
                                    anonymousId: string;
                                    email: string | null;
                                    emailVerifiedAt: string | null;
                                    isEmailBound: boolean;
                                    /** Format: date-time */
                                    createdAt: string;
                                    /** Format: date-time */
                                    updatedAt: string;
                                } | null;
                                tagMaps: {
                                    /** Format: uuid */
                                    feedbackId: string;
                                    tagId: number;
                                    /** Format: date-time */
                                    createdAt: string;
                                    tag: {
                                        id: number;
                                        name: string;
                                    };
                                }[];
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code?: string;
                            /** @example Missing or invalid authorization header */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example FB_NOT_FOUND */
                            code?: string;
                            /** @example Feedback not found */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{feedbackId}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add customer follow-up message to feedback thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    feedbackId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                        senderId?: string;
                        /** Format: uuid */
                        inReplyToMessageId?: string;
                        /** @default [] */
                        attachments?: {
                            /** Format: uri */
                            url: string;
                            filename: string;
                            size: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Follow-up message added successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                feedbackId: string;
                                /** @enum {string} */
                                sender: "customer" | "admin";
                                senderId: string | null;
                                content: string;
                                isQuestion: boolean;
                                inReplyToMessageId: string | null;
                                idempotencyKey: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                attachments: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: uri */
                                    url: string;
                                    filename: string;
                                    sizeBytes: number;
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code?: string;
                            /** @example Missing or invalid authorization header */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code: string;
                            message: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example FB_NOT_FOUND */
                            code?: string;
                            /** @example Feedback not found */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{feedbackId}/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get feedback thread conversation (for user: only their own, for admin: any) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    feedbackId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thread retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                type: "bug" | "feature" | "experience" | "other";
                                /** @enum {string} */
                                status: "new" | "reviewed" | "replied" | "renew" | "resolved";
                                rating: number;
                                /** @enum {string} */
                                locale: "zh_CN" | "zh_Hant" | "en";
                                allowContact: boolean;
                                contact: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    anonymousId: string;
                                    email: string | null;
                                    isEmailBound: boolean;
                                    emailVerifiedAt: string | null;
                                } | null;
                                messages: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    sender: "customer" | "admin";
                                    senderId: string | null;
                                    content: string;
                                    inReplyToMessageId: string | null;
                                    /** Format: date-time */
                                    createdAt: string;
                                    attachments: {
                                        /** Format: uuid */
                                        id: string;
                                        /** Format: uri */
                                        url: string;
                                        filename: string;
                                        sizeBytes: number;
                                        /** Format: date-time */
                                        createdAt: string;
                                    }[];
                                }[];
                                tags: {
                                    id: number;
                                    name: string;
                                }[];
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code?: string;
                            /** @example Missing or invalid authorization header */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example FB_NOT_FOUND */
                            code?: string;
                            /** @example Feedback not found */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
