/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/email/send-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send a verification code to email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Verification code sent */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** Format: uuid */
                                verificationId: string;
                                /** Format: date-time */
                                expiresAt: string;
                                devCode?: string;
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verify email code and get user token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Code verified */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                token: string;
                                /** Format: date-time */
                                expiresAt: string;
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    anonymousId: string;
                                    email: string | null;
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code?: string;
                            /** @example Missing or invalid authorization header */
                            message?: string;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
