/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/signed-upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a signed upload URL for GCS */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        contentType: string;
                        size: number;
                    };
                };
            };
            responses: {
                /** @description Signed upload URL generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                uploadUrl: string;
                                fileUrl: string;
                                requiredHeaders: {
                                    "Content-Type": string;
                                };
                                objectPath: string;
                                /** Format: date-time */
                                expiresAt: string;
                                uploadConstraints: {
                                    /** @enum {string} */
                                    scope: "user" | "anonymous";
                                    maxUploadSizeBytes: number;
                                    allowedContentTypes: string[];
                                    signedUrlExpiresSeconds: number;
                                    rateLimitWindowSeconds: number;
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
