/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Register with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        anonymousId?: string;
                    };
                };
            };
            responses: {
                /** @description Registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                token: string;
                                /** Format: date-time */
                                expiresAt: string;
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    anonymousId: string;
                                    /** Format: email */
                                    email: string;
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                        anonymousId?: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                token: string;
                                /** Format: date-time */
                                expiresAt: string;
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    anonymousId: string;
                                    /** Format: email */
                                    email: string;
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login or register with Google ID token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        idToken: string;
                        anonymousId?: string;
                    };
                };
            };
            responses: {
                /** @description Google login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                token: string;
                                /** Format: date-time */
                                expiresAt: string;
                                identity: {
                                    /** Format: uuid */
                                    id: string;
                                    anonymousId: string;
                                    /** Format: email */
                                    email: string;
                                };
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request a password reset link via email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Reset link sent if account exists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                message: string;
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reset password using token from reset email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        token: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Password reset successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                message: string;
                            };
                            meta?: unknown;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example AUTH_UNAUTHORIZED */
                            code: string;
                            /** @example Missing or invalid authorization header */
                            message: string;
                            details?: Record<string, never>;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
